# Parameter settings for berserker ros driver node

robot:
  port: /dev/ttyACM0
  wheel_base: 0.60
  wheel_diameter: 0.35
  max_speed: 2.0
  min_speed: -2.0
  encoder_lines: 1000
  reduction_ratio: 10.0

odometry:
  odom_id: odom
  child_id: base_footprint
  pub_rate: 30
  tf_publish_flag: true
  pose_covariance_diagonal: [1e-6, 1e-6, 1e-6, 1e-6, 1e-6, 1e-3]
  twist_covariance_diagonal: [1e-3, 1e-5, 1e-6, 1e-6, 1e-6, 1e-2]
